#!/usr/bin/env ruby
require('thor') # for cli parsing
require_relative('lib/banner')

class Script < Thor
  extend Banner

  display("A Simple Scanner")

  desc "--host <IP>", "scans an ip address"
  option :host, required: true
  # options :all => :boolean, :multiple => :boolean
  default_task def main
    puts "Scanning #{options[:host]}"
  end
end
Script.start
